# Used to run the machine in either local environment. This variable can be used for another environment (if any) in future.
machine_location: "local"

local:
  # VM Linux standard timezone
  timezone: "Asia/Kuala_Lumpur"
  # VM cpus and memory
  vb.cpus: 1
  vb.memory: 1024
  vb.vmname: "MyHyper-VM"

  # To choose a default switch to attach to the Hyper-V instance.
  # If none of the existing switches are appropriate, please open the Hyper-V manager to create a new virtual switch.
  config.vm.network.bridge: "Default Switch"

local_static:
  # sudo user inside the VM without password
  vm_user: "vagrant"
