# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'
require 'etc'

# load setting from YAML
settings = YAML.load_file "configurations.yml"
machine_location = settings["machine_location"].downcase

# local
timezone = settings[machine_location]['timezone']
vm_cpus = settings[machine_location]['vb.cpus']
vm_memory = settings[machine_location]['vb.memory']
vm_name = settings[machine_location]['vb.vmname']
vm_network_bridge = settings[machine_location]['config.vm.network.bridge']

# local static
vm_user = settings["#{machine_location}_static"]['vm_user']

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    # Specify the box to be used for booting up a virtual machine
    config.vm.box_url = "https://app.vagrantup.com/generic/boxes/ubuntu2004"
    config.vm.box = "generic/ubuntu2004"
    config.vm.box_version = "3.2.8"

    # Select switch
    config.vm.network "private_network", bridge: vm_network_bridge

    # Customize virtual machine
    config.vm.provider "hyperv" do |vb|
        vb.cpus = vm_cpus
        vb.memory = vm_memory
        vb.vmname = vm_name
    end

    # Using RSync to sync a folder into a Windows box
    config.vm.synced_folder "provision", "/home/#{vm_user}/.ansible", type: "rsync"

    # Run ansible playbook
    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/home/#{vm_user}/.ansible/"
        ansible.playbook = "playbook-setup.yml"
        ## If using pip, you will be able to instal speific version of Ansible but the ansible.cfg will not be auto generated.
        # ansible.install_mode      = "pip"
        # ansible.version           = "2.3.1.0"
        ansible.install        = true
    end

    # Run ansible playbook
    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/home/#{vm_user}/.ansible/"
        ansible.playbook = "playbook-common-utilities.yml"
        ansible.install        = true
        ansible.extra_vars     = {
            vm_user: "#{vm_user}",
        }
    end

end
